remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: [Teaching Interdisciplinary skills to Specialised students at the University of Amsterdam]
show_downloads: [false]

